# Author    : Abhishek Mane <abhishekmane@outlook.in>
# Date      : 03/01/2020

dist: xenial

sudo: required

services:
  - docker

language: python

python:
  - 3.8

install:
  - git clone https://github.com/abhishek-mane/pull-through-registry-update-job.git
  - pip install -r pipenv-requirements.txt
  - pipenv install --deploy --dev
  # - pipenv run pip install -e .

script:
  - ls
  # add tests coverage
  # add pylint analysis

after_success:
  - docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
  - docker build -t docker.pkg.github.com/abhishek-mane/pull-through-registry-update-job/release:latest .
  - docker push docker.pkg.github.com/abhishek-mane/pull-through-registry-update-job/release:latest