# Author    : Abhishek Mane <abhishekmane@outlook.in>
# Date      : 03/01/2020

dist: xenial

sudo: required

services:
  - docker

language: python

python:
  - 3.8

before_script:
  - git clone https://github.com/abhishek-mane/pull-through-registry-update-job.git

install:
  - pip install -r pipenv-requirements.txt
  - pipenv install --deploy --dev
  # - pipenv run pip install -e .